### PR TITLE
Setup project

### PR DESCRIPTION
**Pull request by ichsansandy**
- Learn how to use proper ES6 syntax.
- Use ES6 modules to write modular JavaScript.
- Use webpack to bundle JavaScript.
- Layouting the HTML based on the wireframe
- Using proper git-flow, by using dev branch as default

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @ichsansandy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Weback and related packages added to package.json file
- Project follows the basic structure
- Repo uses a professional readme template

## Required Changes ♻️
_Check the comments under the review._
- Please add `node_modules` to `.gitignore`. This is because the folder is too big to add to version control.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ichsansandy** [comment]
Hi @afanimartin 
Thanks for the review, but I have my .gitignore, 
Here I attached the link to it
https://github.com/ichsansandy/leaderboard-microverse/blob/ab822a98c31273e3dd6e0a9bcb838bf7af802b7f/.gitignore#L42

And also it passed the node_modules checker on github action

**Review by afanimartin — APPROVED** [review]
Hi @ichsansandy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Change made as requested.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by afanimartin** [comment]
> Hi @afanimartin Thanks for the review, but I have my .gitignore, Here I attached the link to it
> 
> https://github.com/ichsansandy/leaderboard-microverse/blob/ab822a98c31273e3dd6e0a9bcb838bf7af802b7f/.gitignore#L42
> 
> And also it passed the node_modules checker on github action

My apologies I must have missed it.

**Pull request merged**
